server:
  port: 0

spring:
  application:
    name: multiplication
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:tcp://h2-database:1521/home/h2-data/multiplication
    username: sa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

amqp.exchange:
  analytics: exchange.analytics

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans